<<<<<<< HEAD
# Generated by Django 5.0.1 on 2024-01-02 18:56

=======
# Generated by Django 5.0 on 2024-01-03 09:03

import django.db.models.deletion
from django.conf import settings
>>>>>>> igggor
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> igggor
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='userr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
=======
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> igggor
            ],
        ),
    ]
