# Generated by Django 5.0 on 2024-01-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0002_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='awards',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
