# Generated by Django 5.0 on 2024-01-04 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0003_profile_awards'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='awards',
            new_name='json',
        ),
    ]
