# Generated by Django 5.0 on 2024-01-06 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0005_remove_profile_json_award_profile_awards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='user',
        ),
    ]
